// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGA.Persistence.Contexts;

#nullable disable

namespace SGA.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410202731_AddAuditoriaEmisiones")]
    partial class AddAuditoriaEmisiones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGA.Domain.Entidades.Configuracion.EstadoAutobus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EstadoAutobuses", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Configuracion.EstadoIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EstadoIncidencias", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Configuracion.EstadoViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EstadoViajes", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Configuracion.TipoAutorizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoAutorizaciones", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Configuracion.TipoIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoIncidencias", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Configuracion.TipoPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoPersonas", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Configuracion.TipoRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoRegistros", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Operaciones.Autorizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("EmitidoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoCobrado")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TipoAutorizacionId")
                        .HasColumnType("int");

                    b.Property<int?>("ViajesRestantes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmitidoPorId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoAutorizacionId");

                    b.ToTable("Autorizaciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Autorizacion_Fechas", "[FechaVencimiento] > [FechaEmision]");
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Operaciones.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EsGrave")
                        .HasColumnType("bit")
                        .HasColumnName("Gravedad");

                    b.Property<int>("EstadoIncidenciaId")
                        .HasColumnType("int");

                    b.Property<string>("EvidenciaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportadoPorConductorId")
                        .HasColumnType("int");

                    b.Property<string>("Resolucion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipoIncidenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ViajeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoIncidenciaId");

                    b.HasIndex("ReportadoPorConductorId");

                    b.HasIndex("TipoIncidenciaId");

                    b.HasIndex("ViajeId");

                    b.ToTable("Incidencias", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Operaciones.RegistroUso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccesoPermitido")
                        .HasColumnType("bit");

                    b.Property<int?>("AutorizacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoRegistroId")
                        .HasColumnType("int");

                    b.Property<int?>("ValidadoPorConductorId")
                        .HasColumnType("int");

                    b.Property<int>("ViajeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorizacionId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoRegistroId");

                    b.HasIndex("ValidadoPorConductorId");

                    b.HasIndex("ViajeId");

                    b.ToTable("RegistrosUso", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Operaciones.TransaccionFinanciera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProcesadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProcesadoPorId");

                    b.ToTable("TransaccionesFinanciera", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TipoPersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique();

                    b.HasIndex("TipoPersonaId");

                    b.ToTable("Personas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Autobus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("EstadoAutobusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAutobusId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Autobuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Autobus_Capacidad", "[Capacidad] > 0");
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraLlegadaEstimada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<int>("RutaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RutaId");

                    b.ToTable("Horarios", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Parada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("RutaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TiempoDesdeOrigen")
                        .HasColumnType("time");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RutaId");

                    b.ToTable("Paradas", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Ruta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("DuracionEstimada")
                        .HasColumnType("time");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rutas", (string)null);
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Viaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AutobusId")
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoViajeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraFinReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraInicioReal")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorarioId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OcupacionActual")
                        .HasColumnType("int");

                    b.Property<int>("RutaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutobusId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("EstadoViajeId");

                    b.HasIndex("HorarioId");

                    b.HasIndex("RutaId");

                    b.ToTable("Viajes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Viaje_OcupacionActual", "[OcupacionActual] >= 0");
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Administrador", b =>
                {
                    b.HasBaseType("SGA.Domain.Entidades.Personas.Persona");

                    b.Property<string>("AreaResponsable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("date");

                    b.Property<string>("NivelAcceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.ToTable("Administradores", null, t =>
                        {
                            t.Property("Id")
                                .HasColumnName("PersonaId");
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Conductor", b =>
                {
                    b.HasBaseType("SGA.Domain.Entidades.Personas.Persona");

                    b.Property<string>("CategoriaLicencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimientoLicencia")
                        .HasColumnType("date");

                    b.Property<string>("LicenciaConducir")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasIndex("LicenciaConducir")
                        .IsUnique()
                        .HasFilter("[LicenciaConducir] IS NOT NULL");

                    b.ToTable("Conductores", null, t =>
                        {
                            t.Property("Id")
                                .HasColumnName("PersonaId");
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Empleado", b =>
                {
                    b.HasBaseType("SGA.Domain.Entidades.Personas.Persona");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("date");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique()
                        .HasFilter("[CodigoEmpleado] IS NOT NULL");

                    b.ToTable("Empleados", null, t =>
                        {
                            t.Property("Id")
                                .HasColumnName("PersonaId");
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Estudiante", b =>
                {
                    b.HasBaseType("SGA.Domain.Entidades.Personas.Persona");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasFilter("[Matricula] IS NOT NULL");

                    b.ToTable("Estudiantes", null, t =>
                        {
                            t.Property("Id")
                                .HasColumnName("PersonaId");
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Operaciones.Autorizacion", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Personas.Persona", "EmitidoPor")
                        .WithMany()
                        .HasForeignKey("EmitidoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGA.Domain.Entidades.Personas.Persona", "Persona")
                        .WithMany("Autorizaciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGA.Domain.Entidades.Configuracion.TipoAutorizacion", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoAutorizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmitidoPor");

                    b.Navigation("Persona");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Operaciones.Incidencia", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Configuracion.EstadoIncidencia", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoIncidenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGA.Domain.Entidades.Personas.Conductor", "ReportadoPor")
                        .WithMany("IncidenciasReportadas")
                        .HasForeignKey("ReportadoPorConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGA.Domain.Entidades.Configuracion.TipoIncidencia", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoIncidenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGA.Domain.Entidades.Transporte.Viaje", "Viaje")
                        .WithMany("Incidencias")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("ReportadoPor");

                    b.Navigation("Tipo");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Operaciones.RegistroUso", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Operaciones.Autorizacion", "Autorizacion")
                        .WithMany("Consumos")
                        .HasForeignKey("AutorizacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SGA.Domain.Entidades.Personas.Persona", "Persona")
                        .WithMany("RegistrosUso")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGA.Domain.Entidades.Configuracion.TipoRegistro", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoRegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGA.Domain.Entidades.Personas.Conductor", "ValidadoPor")
                        .WithMany()
                        .HasForeignKey("ValidadoPorConductorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SGA.Domain.Entidades.Transporte.Viaje", "Viaje")
                        .WithMany("RegistrosAbordaje")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autorizacion");

                    b.Navigation("Persona");

                    b.Navigation("Tipo");

                    b.Navigation("ValidadoPor");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Operaciones.TransaccionFinanciera", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Personas.Persona", "ProcesadoPor")
                        .WithMany()
                        .HasForeignKey("ProcesadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProcesadoPor");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Persona", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Configuracion.TipoPersona", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoPersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Autobus", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Configuracion.EstadoAutobus", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoAutobusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Horario", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Transporte.Ruta", "Ruta")
                        .WithMany("Horarios")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Parada", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Transporte.Ruta", "Ruta")
                        .WithMany("Paradas")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Viaje", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Transporte.Autobus", "Autobus")
                        .WithMany("Viajes")
                        .HasForeignKey("AutobusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGA.Domain.Entidades.Personas.Conductor", "Conductor")
                        .WithMany("ViajesAsignados")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGA.Domain.Entidades.Configuracion.EstadoViaje", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoViajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGA.Domain.Entidades.Transporte.Horario", "Horario")
                        .WithMany("Viajes")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SGA.Domain.Entidades.Transporte.Ruta", "Ruta")
                        .WithMany("Viajes")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autobus");

                    b.Navigation("Conductor");

                    b.Navigation("Estado");

                    b.Navigation("Horario");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Administrador", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Personas.Persona", null)
                        .WithOne()
                        .HasForeignKey("SGA.Domain.Entidades.Personas.Administrador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Conductor", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Personas.Persona", null)
                        .WithOne()
                        .HasForeignKey("SGA.Domain.Entidades.Personas.Conductor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Empleado", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Personas.Persona", null)
                        .WithOne()
                        .HasForeignKey("SGA.Domain.Entidades.Personas.Empleado", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Estudiante", b =>
                {
                    b.HasOne("SGA.Domain.Entidades.Personas.Persona", null)
                        .WithOne()
                        .HasForeignKey("SGA.Domain.Entidades.Personas.Estudiante", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Operaciones.Autorizacion", b =>
                {
                    b.Navigation("Consumos");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Persona", b =>
                {
                    b.Navigation("Autorizaciones");

                    b.Navigation("RegistrosUso");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Autobus", b =>
                {
                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Horario", b =>
                {
                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Ruta", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Paradas");

                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Transporte.Viaje", b =>
                {
                    b.Navigation("Incidencias");

                    b.Navigation("RegistrosAbordaje");
                });

            modelBuilder.Entity("SGA.Domain.Entidades.Personas.Conductor", b =>
                {
                    b.Navigation("IncidenciasReportadas");

                    b.Navigation("ViajesAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
